### PR TITLE
First version automated tests

### PR DESCRIPTION
**Pull request by muhme**
this is a first implementation of automated Cypress based tests, see:

screen1

at the moment for me it is failing from step4 with I18N, is the translation working for you?

screen2

- everything is in directory `tests` if you like another structure, please let me know
- you can see in the README how to run a single test
- default is to run all steps found in `module-tutorial`
- developed on macOS and did a quick test on Windows, there is an error on uninistall from `joomla-cypress` ...
- if you have questions or something to discuss, i prefer a video session
- overall for me the question is this the right direction to continue?

### CODE REVIEW

**Comment by muhme** [comment]
> did a quick test on Windows, there is an error on uninistall from joomla-cypress

during the check it turned out that the uninstallation error is not related to Windows, but to the Joomla version, it works on Joomla 4.4, but no longer on Joomla 5.1 -> please take Joomla 4.4 as target system for the moment

**Comment by HLeithner** [comment]
an option to package a zipfile of the local module and upload it would be great because now you need the exact same path localy and on the webserver. I tested it on a remote server which of course has a completely different path

**Comment by muhme** [comment]
> thanks, now we need an implementation into core ci

and what about
> at the moment for me it is failing from step4 with I18N, is the translation working for you?

see screenshot above - do they also fail for you? the module must work to continure with testing, at the moment only the first 3 samples are running for me; and once the samples are running, i will extend the plugin content checks ...

**Comment by HLeithner** [comment]
hmm seems the translation is not loaded on installation not sure why

**Comment by muhme** [comment]
the installation from the ZIP file also solves the translation problem 😄

**Comment by HLeithner** [comment]
that's interesting, so it's a joomla bug when installing from location. can you create an issue in the joomla repo?

**Comment by muhme** [comment]
👍 i put in on my list, will test before, not sure it is joomla or joomla-cypress

**Comment by muhme** [comment]
> that's interesting, so it's a joomla bug when installing from location. can you create an issue in the joomla repo?

@HLeithner I have checked and found out the following: It is possible to install the module with `installExtensionFromFolder()` with path 'manual-examples/module-tutorial/step4_languages', but for the language translation to work, the path must be 'manual-examples/module-tutorial/step4_languages/mod_hello'. This is strange, but for me more natural to specify the folder of the module. Anyway, I have on my TODO list to qualify joomla-cypress-documentation I will add this detail there and give an example.

**Pull request merged**
